services:
    travel-blog:
        container_name: travel-blog
        image: wlczak/travel-blog:latest
        labels:
            - com.centurylinklabs.watchtower.enable=true
        ports:
            - "9123:80"
        #volumes:
        #    - ./:/var/www/html
        #environment:
        #    DATABASE_URL: "mysql://root:root@db:3306/travel-blog"
        restart: always
        init: true
        networks:
            - universal-db-network

networks:
    universal-db-network:
        driver: bridge
        name: universal-db-network
        external: true
