name: Composer

on: [push, pull_request]

jobs:
    Nette_tests_linux:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3" # Choose the PHP version you need

            - name: Install Composer Dependencies
              run: composer install

            - name: Run Latte Tests
              run: cd tests ; php testAutorun.php;
    Nette_tests_macOS:
        runs-on: macos-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3" # Choose the PHP version you need

            - name: Install Composer Dependencies
              run: composer install

            - name: Run Latte Tests
              run: cd tests ; php testAutorun.php;
    Nette_tests_windows:
        runs-on: windows-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3" # Choose the PHP version you need

            - name: Install Composer Dependencies
              run: composer install

            - name: Run Latte Tests
              run: cd tests ; php testAutorun.php;
